#静态资源访问前缀,默认为/**
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: [ classpath:/statics/ ]

  datasource:
    url: jdbc:mysql://180.76.185.155:3306/springboot
    username: springboot
    password: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver

#    druid:
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: admin
#        reset-enable: false

#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions:
#      proxy-filters: stat,wall

#    redis:
#      url: 127.0.0.1


#配置mybatis规则
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml