#静态资源访问前缀
spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://localhost:3306/studyJava
    username: studyJava
    password: studyJava
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions:
      proxy-filters: stat,wall

    redis:
      url: 127.0.0.1


#配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml